_BASE_: './Base-RCNN-FPN-COCOA-cls.yaml'
OUTPUT_DIR: ../data/aisformer_model_outputs/cocoa_cls_no_occluder_test_model/
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_400ep_LSJ/42019571/model_final_14d201.pkl" 
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    NAME: AISFormer
DATASETS:
  TRAIN: ("cocoa_cls_train_modified",)
  TEST: ("cocoa_cls_val_modified",)
AISFORMER:
  INVISIBLE_MASK_LOSS: True
  N_LAYERS: 1
  N_HEADS: 2
  EMB_DIM: 256