_BASE_: './Base-RCNN-FPS-COCO_ASBU.yaml'
OUTPUT_DIR: ../data/aisformer_model_outputs/coco_asbu_2/
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_400ep_LSJ/42019571/model_final_14d201.pkl" 
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    NAME: AISFormer
AISFORMER:
  INVISIBLE_MASK_LOSS: True
  N_LAYERS: 1
  N_HEADS: 2
  EMB_DIM: 256